//text
const TEXT_BLACK_COLOR = '#000000';
const PLACEHOLDER_TEXT_INPUT_COLOR = '#8f8f8f';
const TEXT_SIGNUP = '#0d5af4';
const TEXT_SUGGESS_GRAY = '#f49d2b';
const ERROR_COLOR = '#f03737';
// TEXT COLOR IN TEXT INPUT STORY
const TEXT_BLUE_COLOR = '#1facf8';
const TEXT_GREEN_COLOR = '#51f56f';
const TEXT_YELLOW_COLOR = '#fafa42';
const TEXT_RED_COLOR = '#ff5656';
const TEXT_ORANGE_COLOR = '#fbc65b';
const TEXT_PINK_COLOR = '#fa3fed';
const TEXT_LIGHT_PINK_COLOR = '#fe86f6';
const TEXT_PURPLE_COLOR = '#9d38fc';
const TEXT_LIGHT_PURPLE_COLOR = '#c184fa';
//
const LIGHT_GRAY = '#5f5f5f';
const INPUT_GRAY = '#e8e8e8';
const INPUT_STORY_GRAY = '#cccccc';
//background
const PRIMARY_COLOR = '#000000';
const BG_EDIT_STORY_COLOR = '#181818';
const WHITE_COLOR = '#ffffff';
const FACEBOOK_COLOR = '#4267B2';
const ADD_STORY_COLOR = '#578df8';
//--- Edit Story
const LINEAR_BLACK_COLOR = ['#2a2a2a', '#1b1b1b', '#181818'];
const LINEAR_PUPER_COLOR = ['#7a2fd1', '#701fd3', '#4a1bd9'];
const LINEAR_PINK_COLOR = ['#f67cbb', '#f162ac', '#f85e72ff'];
const LINEAR_BLUE_COLOR = ['#76d5f5', '#688ef5', '#8475f9'];
const LINEAR_GREEN_COLOR = ['#aef787', '#8ef66f', '#6df586'];

const LIST_TEXT_COLOR = [
  WHITE_COLOR,
  TEXT_BLACK_COLOR,
  TEXT_BLUE_COLOR,
  TEXT_GREEN_COLOR,
  TEXT_YELLOW_COLOR,
  TEXT_RED_COLOR,
  TEXT_ORANGE_COLOR,
  TEXT_PINK_COLOR,
  TEXT_LIGHT_PINK_COLOR,
  TEXT_PURPLE_COLOR,
  TEXT_LIGHT_PURPLE_COLOR,
  INPUT_GRAY,
  LIGHT_GRAY,
];

// message
const GREEN_ONLINE_COLOR = '#5bef36';
const MESSAGE_GRAY_COLOR = '#f1f1f1';
const DOT_NEW_MESSAGE_COLOR = '#f64040';

export const COLORS = {
  TEXT_BLACK_COLOR,
  PLACEHOLDER_TEXT_INPUT_COLOR,
  PRIMARY_COLOR,
  LIGHT_GRAY,
  WHITE_COLOR,
  FACEBOOK_COLOR,
  TEXT_SIGNUP,
  ERROR_COLOR,
  INPUT_GRAY,
  TEXT_SUGGESS_GRAY,
  GREEN_ONLINE_COLOR,
  MESSAGE_GRAY_COLOR,
  DOT_NEW_MESSAGE_COLOR,
  BG_EDIT_STORY_COLOR,
  LINEAR_BLACK_COLOR,
  LINEAR_PUPER_COLOR,
  LINEAR_PINK_COLOR,
  LINEAR_BLUE_COLOR,
  LINEAR_GREEN_COLOR,
  ADD_STORY_COLOR,
  INPUT_STORY_GRAY,
  TEXT_BLUE_COLOR,
  TEXT_GREEN_COLOR,
  TEXT_YELLOW_COLOR,
  TEXT_RED_COLOR,
  TEXT_ORANGE_COLOR,
  TEXT_PINK_COLOR,
  TEXT_LIGHT_PINK_COLOR,
  TEXT_PURPLE_COLOR,
  TEXT_LIGHT_PURPLE_COLOR,
  LIST_TEXT_COLOR,
};
